version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_product_api
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: products_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: nestjs_product_api
    ports:
      - '3000:3000'
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - postgres
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: products_db

volumes:
  pgdata:
